imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug: "%kernel.debug%"
    use_controller: false
    bundles:
        - FrontBundle
        - AdminBundle
    node: "%node_path%"
    filters:
        cssrewrite:
            apply_to: "\.css$"
        lessphp:
            apply_to: "\.less$"
            #file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        #less:
            #node: "%node_path%"
            #node_paths: ["%node_modules_path%"]
            #apply_to: "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

a2lix_translation_form:
    locales: [es, ca, en]
    manager_registry: doctrine

stof_doctrine_extensions:
    default_locale: es
    translation_fallback: true
    orm:
        default:
            sluggable: true
            translatable: true
            timestampable: true

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

services:
    punk_ave.file_uploader:
        class: Blog\CoreBundle\Service\FileUploader\FileUploader
        arguments:
            - file_base_path: '%file_uploader.file_base_path%'
              web_base_path: '%file_uploader.web_base_path%'
              request: '@request'
              file_manager: '@punk_ave.file_uploader_file_manager'
              allowed_extensions: '%file_uploader.allowed_extensions%'
              sizes: '%file_uploader.sizes%'
              originals: '%file_uploader.originals%'
              max_number_of_files: '%file_uploader.max_number_of_files%'
              router: '@router'
        scope: request

    punk_ave.file_uploader_file_manager:
        class: Blog\CoreBundle\Service\FileUploader\FileManager
        arguments:
            # For bc reasons we're not changing the names of the parameters
            - file_base_path: '%file_uploader.file_base_path%'

jms_i18n_routing:
    default_locale: es
    locales: [es, ca, en]
    strategy: prefix
